# Generated by Django 5.2.11 on 2026-02-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Period 1, Morning Session", max_length=50
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Attendance Period",
                "verbose_name_plural": "Attendance Periods",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National Holiday"),
                            ("school", "School Holiday"),
                            ("exam", "Examination"),
                            ("event", "School Event"),
                            ("vacation", "Vacation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_multi_day", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Holiday Calendar",
                "verbose_name_plural": "Holiday Calendar",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("absence", "Absence Alert"),
                            ("low_attendance", "Low Attendance Warning"),
                            ("consecutive_absence", "Consecutive Absence Alert"),
                            ("late_arrival", "Late Arrival"),
                            ("leave_approved", "Leave Approved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_to_student", models.BooleanField(default=False)),
                ("sent_to_parent", models.BooleanField(default=False)),
                ("sent_to_teacher", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Notification",
                "verbose_name_plural": "Attendance Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=75.0,
                        help_text="Minimum attendance percentage required",
                        max_digits=5,
                    ),
                ),
                (
                    "grace_days",
                    models.IntegerField(
                        default=5, help_text="Additional grace days allowed"
                    ),
                ),
                (
                    "consecutive_absence_alert",
                    models.IntegerField(
                        default=3,
                        help_text="Alert after this many consecutive absences",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policies",
                        to="academic.class",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Policy",
                "verbose_name_plural": "Attendance Policies",
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick Leave"),
                            ("personal", "Personal Leave"),
                            ("family", "Family Emergency"),
                            ("medical", "Medical Appointment"),
                            ("sports", "Sports Event"),
                            ("academic", "Academic Event"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days", models.IntegerField(default=1)),
                ("reason", models.TextField()),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_documents/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_remarks", models.TextField(blank=True)),
                ("auto_mark_attendance", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_principal": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of month")),
                ("total_working_days", models.IntegerField(default=0)),
                ("present_days", models.IntegerField(default=0)),
                ("absent_days", models.IntegerField(default=0)),
                ("late_days", models.IntegerField(default=0)),
                ("excused_days", models.IntegerField(default=0)),
                ("half_day_days", models.IntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
                "ordering": ["-month", "student"],
                "unique_together": {("student", "month")},
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused/Leave"),
                            ("half_day", "Half Day"),
                            ("early_departure", "Early Departure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Any additional notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_teacher": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="attendance.leaveapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Attendance",
                "verbose_name_plural": "Daily Attendance Records",
                "ordering": ["-date", "student"],
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="attendance__student_ed8b4b_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="attendance__date_a41095_idx"
                    ),
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="PeriodAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="attendance.attendanceperiod",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_teacher": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_attendance_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_attendance",
                        to="academic.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_attendance",
                        to="academic.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_attendance",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period Attendance",
                "verbose_name_plural": "Period Attendance Records",
                "ordering": ["-date", "period__order", "student"],
                "indexes": [
                    models.Index(
                        fields=["student", "date", "period"],
                        name="attendance__student_361a0f_idx",
                    ),
                    models.Index(
                        fields=["school_class", "section", "date"],
                        name="attendance__school__ee54c5_idx",
                    ),
                ],
                "unique_together": {("student", "date", "period")},
            },
        ),
    ]
