# Generated by Django 5.2.11 on 2026-02-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_name",
                    models.CharField(
                        help_text="e.g., 2024-2025", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the current active academic year",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=20, unique=True)),
                ("subject_name", models.CharField(max_length=200)),
                (
                    "is_credit",
                    models.BooleanField(
                        default=True, help_text="Does this subject carry credits?"
                    ),
                ),
                (
                    "credit_hours",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="Can students choose not to take this?"
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("theory", "Theory Only"),
                            ("practical", "Practical Only"),
                            ("hybrid", "Theory + Practical"),
                        ],
                        default="theory",
                        max_length=20,
                    ),
                ),
                (
                    "theory_full_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                (
                    "practical_full_marks",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "passing_percentage",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "syllabus",
                    models.TextField(blank=True, help_text="Detailed syllabus/outcome"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["subject_code"],
            },
        ),
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subject Category",
                "verbose_name_plural": "Subject Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=20, unique=True)),
                ("class_name", models.CharField(max_length=100)),
                (
                    "grade_level",
                    models.IntegerField(help_text="Numeric grade level (e.g., 1-12)"),
                ),
                (
                    "min_credits",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                (
                    "max_credits",
                    models.DecimalField(decimal_places=2, default=24.0, max_digits=5),
                ),
                ("min_optional_subjects", models.IntegerField(default=0)),
                ("max_optional_subjects", models.IntegerField(default=2)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "compulsory_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compulsory_for_classes",
                        to="academic.subject",
                    ),
                ),
                (
                    "optional_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="optional_for_classes",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["grade_level", "class_code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(help_text="e.g., A, B, C", max_length=10),
                ),
                ("max_capacity", models.PositiveIntegerField(default=40)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_teacher": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="academic.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["school_class", "section_name"],
                "unique_together": {("school_class", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("first", "First Semester"),
                            ("second", "Second Semester"),
                            ("third", "Third Semester"),
                            ("summer", "Summer Term"),
                            ("quarter_1", "Quarter 1"),
                            ("quarter_2", "Quarter 2"),
                            ("quarter_3", "Quarter 3"),
                            ("quarter_4", "Quarter 4"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Mark as the currently active semester"
                    ),
                ),
                (
                    "registration_open",
                    models.BooleanField(
                        default=False, help_text="Allow student registrations"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academic.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "ordering": ["academic_year", "start_date"],
                "unique_together": {("academic_year", "name")},
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="academic.subjectcategory",
            ),
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        blank=True,
                        help_text="Student roll number in class",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("promoted", "Promoted"),
                            ("repeated", "Repeated"),
                            ("transferred", "Transferred"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("final_grade", models.CharField(blank=True, max_length=5)),
                ("remarks", models.TextField(blank=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academic.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academic.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Enrollment",
                "verbose_name_plural": "Class Enrollments",
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "school_class")},
            },
        ),
        migrations.CreateModel(
            name="StudentSubjectEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("final_grade", models.CharField(blank=True, max_length=5)),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("dropped_date", models.DateTimeField(blank=True, null=True)),
                ("dropped_reason", models.TextField(blank=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academic.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Subject Enrollment",
                "verbose_name_plural": "Student Subject Enrollments",
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "subject", "semester")},
            },
        ),
        migrations.CreateModel(
            name="SubjectPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True,
                        help_text="Minimum grade required (e.g., C, B)",
                        max_length=5,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Is this prerequisite mandatory?"
                    ),
                ),
                (
                    "prerequisite_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_prerequisite_for",
                        to="academic.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites_details",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Prerequisite",
                "verbose_name_plural": "Subject Prerequisites",
                "unique_together": {("subject", "prerequisite_subject")},
            },
        ),
        migrations.CreateModel(
            name="TeacherClassAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_periods",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of periods per week"
                    ),
                ),
                (
                    "schedule_notes",
                    models.TextField(blank=True, help_text="Day/time schedule notes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academic.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academic.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academic.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"is_teacher": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Class Assignment",
                "verbose_name_plural": "Teacher Class Assignments",
                "ordering": ["teacher", "school_class", "subject"],
                "unique_together": {
                    ("teacher", "subject", "school_class", "section", "semester")
                },
            },
        ),
    ]
