# Generated by Django 5.2.11 on 2026-02-15 09:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("mid_term", "Mid-Term Examination"),
                            ("final", "Final Examination"),
                            ("unit_test", "Unit Test"),
                            ("practical", "Practical Examination"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "weightage_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Weightage in overall result calculation",
                        max_digits=5,
                    ),
                ),
                ("is_timetable_published", models.BooleanField(default=False)),
                (
                    "timetable_published_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_result_published", models.BooleanField(default=False)),
                ("result_published_date", models.DateTimeField(blank=True, null=True)),
                ("allow_students_to_view_results", models.BooleanField(default=False)),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=6
                    ),
                ),
                (
                    "passing_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academic.semester",
                    ),
                ),
                (
                    "timetable_published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetables_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "theory_full_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "practical_full_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("passing_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_minutes", models.IntegerField()),
                ("venue", models.CharField(blank=True, max_length=100)),
                ("is_marks_entered", models.BooleanField(default=False)),
                ("marks_entered_at", models.DateTimeField(blank=True, null=True)),
                ("is_marks_verified", models.BooleanField(default=False)),
                ("marks_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_details_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="exams.exam",
                    ),
                ),
                (
                    "invigilators",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_teacher": True},
                        related_name="invigilated_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marks_entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marks_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marks_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marks_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_details",
                        to="academic.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_details",
                        to="academic.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_details",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Detail",
                "verbose_name_plural": "Exam Details",
                "ordering": ["exam_date", "start_time"],
                "unique_together": {("exam", "subject", "school_class", "section")},
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., CBSE Scale, IB Scale", max_length=100
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_scales",
                        to="academic.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grading Scale",
                "verbose_name_plural": "Grading Scales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportCardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "header_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="report_cards/headers/"
                    ),
                ),
                ("footer_text", models.TextField(blank=True)),
                ("show_signature", models.BooleanField(default=True)),
                ("show_photo", models.BooleanField(default=True)),
                ("show_attendance", models.BooleanField(default=True)),
                ("show_remarks", models.BooleanField(default=True)),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for report card",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_card_templates",
                        to="academic.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Card Template",
                "verbose_name_plural": "Report Card Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentExamStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("medical", "Medical Leave"),
                            ("disqualified", "Disqualified"),
                            ("exempted", "Exempted"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_statuses",
                        to="exams.examdetail",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Exam Status",
                "verbose_name_plural": "Student Exam Statuses",
                "ordering": ["-recorded_at"],
                "unique_together": {("student", "exam_detail")},
            },
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theory_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "practical_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=5)),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("theory_grade", models.CharField(blank=True, max_length=5)),
                ("practical_grade", models.CharField(blank=True, max_length=5)),
                ("has_passed", models.BooleanField(default=False)),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="exams.examdetail",
                    ),
                ),
                (
                    "exam_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.studentexamstatus",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Result",
                "verbose_name_plural": "Student Results",
                "ordering": ["-created_at"],
                "unique_together": {("student", "exam_detail")},
            },
        ),
        migrations.CreateModel(
            name="ResultModificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                ("field_changed", models.CharField(max_length=50)),
                ("old_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_principal": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_logs",
                        to="exams.studentresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Modification Log",
                "verbose_name_plural": "Result Modification Logs",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(help_text="e.g., A+, A, B+", max_length=5)),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=2, help_text="For GPA calculation", max_digits=4
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Outstanding, Excellent",
                        max_length=50,
                    ),
                ),
                (
                    "grading_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="exams.gradingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Range",
                "verbose_name_plural": "Grade Ranges",
                "ordering": ["-min_percentage"],
                "unique_together": {("grading_scale", "grade")},
            },
        ),
        migrations.CreateModel(
            name="GeneratedReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="report_cards/generated/"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_distributed", models.BooleanField(default=False)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distributed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_cards_distributed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="exams.exam",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_cards_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_cards",
                        to="exams.reportcardtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report Card",
                "verbose_name_plural": "Generated Report Cards",
                "ordering": ["-generated_at"],
                "unique_together": {("student", "exam")},
            },
        ),
        migrations.CreateModel(
            name="StudentOverallResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks_obtained",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "total_full_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=5)),
                (
                    "grade_point_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("class_rank", models.IntegerField(blank=True, null=True)),
                ("section_rank", models.IntegerField(blank=True, null=True)),
                ("subjects_appeared", models.IntegerField(default=0)),
                ("subjects_passed", models.IntegerField(default=0)),
                ("subjects_failed", models.IntegerField(default=0)),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("compartment", "Compartment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Overall Result",
                "verbose_name_plural": "Student Overall Results",
                "ordering": ["-percentage"],
                "unique_together": {("student", "exam")},
            },
        ),
    ]
